const templateArray = [
  {
    formTitle: "Contact Us",
    formSubheading:
      "We'd love to hear from you! Fill out the form below and we'll get in touch with you soon.",
    formFields: [
      {
        formName: "fullName",
        placeholderName: "Enter your full name",
        formLabel: "Full Name",
        fieldType: "text",
        fieldRequired: true,
      },
      {
        formName: "email",
        placeholderName: "Enter your email address",
        formLabel: "Email",
        fieldType: "email",
        fieldRequired: true,
      },
      {
        formName: "phone",
        placeholderName: "Enter your phone number",
        formLabel: "Phone Number",
        fieldType: "tel",
        fieldRequired: false,
      },
      {
        formName: "message",
        placeholderName: "Enter your message",
        formLabel: "Message",
        fieldType: "textarea",
        fieldRequired: true,
      },
    ],
  },
  {
    formTitle: "Event Registration",
    formSubheading:
      "Register for our upcoming event by filling out the form below.",
    formFields: [
      {
        formName: "fullName",
        placeholderName: "Enter your full name",
        formLabel: "Full Name",
        fieldType: "text",
        fieldRequired: true,
      },
      {
        formName: "email",
        placeholderName: "Enter your email address",
        formLabel: "Email",
        fieldType: "email",
        fieldRequired: true,
      },
      {
        formName: "phone",
        placeholderName: "Enter your phone number",
        formLabel: "Phone Number",
        fieldType: "tel",
        fieldRequired: false,
      },
      {
        formName: "eventDate",
        placeholderName: "Select the event date",
        formLabel: "Event Date",
        fieldType: "date",
        fieldRequired: true,
      },
      {
        formName: "attending",
        placeholderName: "Will you attend?",
        formLabel: "Will Attend?",
        fieldType: "radio",
        fieldRequired: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
    ],
  },
  {
    formTitle: "Customer Satisfaction Survey",
    formSubheading: "Help us improve by sharing your feedback.",
    formFields: [
      {
        formName: "customerName",
        placeholderName: "Enter your name",
        formLabel: "Name",
        fieldType: "text",
        fieldRequired: false,
      },
      {
        formName: "serviceRating",
        placeholderName: "Rate our service",
        formLabel: "Service Rating",
        fieldType: "radio",
        fieldRequired: true,
        options: [
          { label: "Excellent", value: "excellent" },
          { label: "Good", value: "good" },
          { label: "Fair", value: "fair" },
          { label: "Poor", value: "poor" },
        ],
      },
      {
        formName: "improvements",
        placeholderName: "What can we improve?",
        formLabel: "Suggestions for Improvement",
        fieldType: "textarea",
        fieldRequired: false,
      },
      {
        formName: "contactConsent",
        placeholderName: "",
        formLabel: "Can we contact you for more details?",
        fieldType: "checkbox",
        fieldRequired: false,
      },
    ],
  },
  {
    formTitle: "Place Your Order",
    formSubheading: "Complete the form to place your order.",
    formFields: [
      {
        formName: "fullName",
        placeholderName: "Enter your full name",
        formLabel: "Full Name",
        fieldType: "text",
        fieldRequired: true,
      },
      {
        formName: "email",
        placeholderName: "Enter your email address",
        formLabel: "Email",
        fieldType: "email",
        fieldRequired: true,
      },
      {
        formName: "address",
        placeholderName: "Enter your shipping address",
        formLabel: "Shipping Address",
        fieldType: "textarea",
        fieldRequired: true,
      },
      {
        formName: "quantity",
        placeholderName: "Enter the quantity",
        formLabel: "Quantity",
        fieldType: "number",
        fieldRequired: true,
      },
      {
        formName: "paymentMethod",
        placeholderName: "Select a payment method",
        formLabel: "Payment Method",
        fieldType: "select",
        fieldRequired: true,
        options: ["Credit Card", "PayPal", "Bank Transfer", "Cash on Delivery"],
      },
    ],
  },
  {
    formTitle: "Subscribe to Our Newsletter",
    formSubheading: "Stay updated with our latest news and offers.",
    formFields: [
      {
        formName: "email",
        placeholderName: "Enter your email address",
        formLabel: "Email",
        fieldType: "email",
        fieldRequired: true,
      },
      {
        formName: "preferences",
        placeholderName: "Select your preferences",
        formLabel: "Topics of Interest",
        fieldType: "checkbox",
        fieldRequired: false,
        options: [
          { label: "Technology", value: "technology" },
          { label: "Health", value: "health" },
          { label: "Finance", value: "finance" },
          { label: "Lifestyle", value: "lifestyle" },
        ],
      },
    ],
  },
  {
    formTitle: "Book an Appointment",
    formSubheading: "Schedule a consultation at your convenience.",
    formFields: [
      {
        formName: "name",
        placeholderName: "Enter your full name",
        formLabel: "Full Name",
        fieldType: "text",
        fieldRequired: true,
      },
      {
        formName: "email",
        placeholderName: "Enter your email",
        formLabel: "Email",
        fieldType: "email",
        fieldRequired: true,
      },
      {
        formName: "appointmentDate",
        placeholderName: "Select a date",
        formLabel: "Preferred Date",
        fieldType: "date",
        fieldRequired: true,
      },
      {
        formName: "appointmentTime",
        placeholderName: "Select a time",
        formLabel: "Preferred Time",
        fieldType: "time",
        fieldRequired: true,
      },
      {
        formName: "reason",
        placeholderName: "Enter the reason for your appointment",
        formLabel: "Reason for Appointment",
        fieldType: "textarea",
        fieldRequired: true,
      },
    ],
  },
  {
    formTitle: "Customer Satisfaction Survey",
    formSubheading: "Help us improve by sharing your feedback.",
    formFields: [
      {
        formName: "customerName",
        placeholderName: "Enter your name",
        formLabel: "Name",
        fieldType: "text",
        fieldRequired: false,
      },
      {
        formName: "serviceRating",
        placeholderName: "Rate our service",
        formLabel: "Service Rating",
        fieldType: "radio",
        fieldRequired: true,
        options: [
          { label: "Excellent", value: "excellent" },
          { label: "Good", value: "good" },
          { label: "Fair", value: "fair" },
          { label: "Poor", value: "poor" },
        ],
      },
      {
        formName: "improvements",
        placeholderName: "What can we improve?",
        formLabel: "Suggestions for Improvement",
        fieldType: "textarea",
        fieldRequired: false,
      },
      {
        formName: "contactConsent",
        placeholderName: "",
        formLabel: "Can we contact you for more details?",
        fieldType: "checkbox",
        fieldRequired: false,
      },
    ],
  },
  {
    formTitle: "Event Registration",
    formSubheading:
      "Register for our upcoming event by filling out the form below.",
    formFields: [
      {
        formName: "fullName",
        placeholderName: "Enter your full name",
        formLabel: "Full Name",
        fieldType: "text",
        fieldRequired: true,
      },
      {
        formName: "email",
        placeholderName: "Enter your email address",
        formLabel: "Email",
        fieldType: "email",
        fieldRequired: true,
      },
      {
        formName: "phone",
        placeholderName: "Enter your phone number",
        formLabel: "Phone Number",
        fieldType: "tel",
        fieldRequired: false,
      },
      {
        formName: "eventDate",
        placeholderName: "Select the event date",
        formLabel: "Event Date",
        fieldType: "date",
        fieldRequired: true,
      },
      {
        formName: "attending",
        placeholderName: "Will you attend?",
        formLabel: "Will Attend?",
        fieldType: "radio",
        fieldRequired: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
    ],
  },
];
export default templateArray;
